name: gpuhackathon
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cupy~=13.3.0
  - cupy-xarray~=0.1.4
  - dask-jobqueue~=0.9.0
  - git-lfs~=3.6.1
  - graphviz~=12.2.1
  - rapidsai-nightly::kvikio>=25.04.00a
  - jupyterlab~=4.3.5
  - nvidia-dali-python>=1.45.0
  - nvtx~=0.2.11
  - python=3.12
  - pip~=25.0
  - pytorch~=2.6.0
  - segmentation-models-pytorch~=0.4.0
  - xarray>=2025.3.0
  - pip:
    - nvidia-nvcomp-cu12
    - torchviz
    - zarr[gpu] @ git+https://github.com/akshaysubr/zarr-python.git@gpu-codecs
