name: gpuhackathon
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cupy~=13.3.0
  - dask-jobqueue~=0.9.0
  - rapidsai::kvikio>=25.04.00
  - jupyterlab~=4.3.5
  - nvcomp~=4.2.0.14
  - nvidia-dali-python~=1.45.0
  - nvtx~=0.2.11
  - python=3.12
  - pip~=25.0
  - pytorch~=2.6.0
  - segmentation-models-pytorch~=0.4.0
  - xarray>=2025.4.0
  - zarr~=3.0.8
  - pip:
    - zarr @ git+https://github.com/akshaysubr/zarr-python.git@gpu-codecs
